version: "3.9"

services:
  video-gen:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
